
from enum import Enum

class KeywordCombination(Enum):

    MANTER_ORIGINAL = 1
    INCLUIR_MAIUSCULAS = 2
    REMOVER_CARACTERES_ESPECIAIS = 3
    INCLUIR_MAIUSCULAS_E_REMOVER_CARACTERES_ESPECIAIS = 4